# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from pb import sleepservice_pb2 as pb_dot_sleepservice__pb2


class SleepTaskerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Sleep = channel.unary_unary(
        '/sleepservice.SleepTasker/Sleep',
        request_serializer=pb_dot_sleepservice__pb2.SleepTask.SerializeToString,
        response_deserializer=pb_dot_sleepservice__pb2.SleepResponse.FromString,
        )
    self.SleepStream = channel.unary_stream(
        '/sleepservice.SleepTasker/SleepStream',
        request_serializer=pb_dot_sleepservice__pb2.SleepTasks.SerializeToString,
        response_deserializer=pb_dot_sleepservice__pb2.SleepResponse.FromString,
        )


class SleepTaskerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Sleep(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SleepStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SleepTaskerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Sleep': grpc.unary_unary_rpc_method_handler(
          servicer.Sleep,
          request_deserializer=pb_dot_sleepservice__pb2.SleepTask.FromString,
          response_serializer=pb_dot_sleepservice__pb2.SleepResponse.SerializeToString,
      ),
      'SleepStream': grpc.unary_stream_rpc_method_handler(
          servicer.SleepStream,
          request_deserializer=pb_dot_sleepservice__pb2.SleepTasks.FromString,
          response_serializer=pb_dot_sleepservice__pb2.SleepResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sleepservice.SleepTasker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
